CREATE SCHEMA IF NOT EXISTS comment;

DROP TABLE IF EXISTS comment.comments CASCADE;

CREATE TABLE comment.comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       TEXT NOT NULL,
    event_id   BIGINT,
    author_id  BIGINT,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
