CREATE SCHEMA IF NOT EXISTS request;

DROP TABLE IF EXISTS request.request CASCADE;

CREATE TABLE request.request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id     BIGINT      NOT NULL,
    requester_id BIGINT      NOT NULL,
    status       VARCHAR(15) NOT NULL
);
