server:
  port: 8080

spring:
  webflux:
    resources:
      add-mappings: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/users/*/comments/**, /admin/comments/**

        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**,/users/*/events/*/requests/**,/users/*/events/*/requests


        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/events/**, /users/*/events/**, /admin/events/**, /compilations/**, /admin/compilations/**, /admin/categories/**, /categories/**

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, health, info

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.actuate.endpoint.web.servlet: DEBUG
    org.springframework.boot.actuate: DEBUG
    reactor.netty: DEBUG
