server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: main-service-categories
          uri: lb://main-service
          predicates:
            - Path=/categories/**
        - id: main-service-admin
          uri: lb://main-service
          predicates:
            - Path=/admin/**
        - id: main-service-users
          uri: lb://main-service
          predicates:
            - Path=/users/**
        - id: main-service-events
          uri: lb://main-service
          predicates:
            - Path=/events/**
        - id: main-service-compilations
          uri: lb://main-service
          predicates:
            - Path=/compilations/**
        - id: stats-server-hit
          uri: lb://stats-server
          predicates:
            - Path=/hit/**
        - id: stats-server-stats
          uri: lb://stats-server
          predicates:
            - Path=/stats/**


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, health, info

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.actuate.endpoint.web.servlet: DEBUG
    org.springframework.boot.actuate: DEBUG
    reactor.netty: DEBUG
