server:
  port: 8080

spring:
  webflux:
    resources:
      add-mappings: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users
            - Path=/admin/users/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/users/*/events/*/comments
            - Path=/users/*/events/*/comments/**
            - Path=/events/*/comments
            - Path=/events/*/comments/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests
            - Path=/users/*/requests/**
            - Path=/requests
            - Path=/requests/**
        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit
            - Path=/hit/**
            - Path=/stats
            - Path=/stats/**
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/events/**, /users/*/events/**, /admin/events/**, /compilations/**, /admin/compilations/**, /admin/categories/**, /categories/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, health, info

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.actuate.endpoint.web.servlet: DEBUG
    org.springframework.boot.actuate: DEBUG
    reactor.netty: DEBUG
