server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/users/*/events/*/comments/**, /events/*/comments/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /requests/**
        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit/**, /stats/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**, /users/*/events/**, /users/*/events/*/requests/**, /events/**
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/categories/**, /admin/categories/**, /admin/compilations/**, /compilations/**


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, health, info

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.actuate.endpoint.web.servlet: DEBUG
    org.springframework.boot.actuate: DEBUG
    reactor.netty: DEBUG
